apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: demo
type: Opaque
data:
  # base64 of: postgresql+psycopg://app:app_password@postgres.demo.svc.cluster.local:5432/appdb
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vYXBwOmFwcF9wYXNzd29yZEBwb3N0Z3Jlcy5kZW1vLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvYXBwZGI=