apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-app
  template:
    metadata:
      labels:
        app: mini-app
    spec:
      containers:
        - name: app
          image: mini-kube-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_URL
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 10
